version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    container_name: api-h2-docker-container
    ports:
      - 8080:8080

networks:
  default:
    name: api-h2-docker-network