version: '3.8'

services:
  api:
    image: springboot-todo-h2-api-docker      
    container_name: springboot-todo-h2-api-docker-container
    ports:
      - 8080:8080

networks:
  default:
    name: springboot-todo-h2-api-docker-network