# Name this image like  springboot-todo-h2-api-docker-basic
# Previous build the docker image execute the following steps
# 1.  mvn clean package

FROM openjdk:17
EXPOSE 8080

# Create app directory
WORKDIR /usr/src/app
ADD target/springboot-todo-h2-api-docker.jar /usr/src/app/springboot-todo-h2-api-docker.jar

ENTRYPOINT ["java", "-jar", "springboot-todo-h2-api-docker.jar" ]